# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: codefoster
subtitle:
description:
author: Jeremy Foster
language: en
timezone: 

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://codefoster.com
root: /
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: Other
category_map:
tag_map:

#Disqus
disqus_shortname: codefoster

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: chan

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy: 
  type: git
  repo: https://github.com/codefoster/codefoster.com.git
  branch: azure

# Aliases
## https://github.com/hexojs/hexo-generator-alias
alias:
  contact: about
  me: about
  contact.aspx: about
  # blog/feed: rss
  # feed: rss
  How-the-WinJSUIViewBox-Actually-Works/: /viewboxhow/
  Children-of-the-Nations: cotni
  blend-design-execute-interact: blend
  open-existing-nodejs-project-in-visual-studio: existingnode
  resharper-7-is-released: rs7released
  A-Primer-on-LINQ-and-Lambda: linqlambda
  articles/codeshow: codeshow
  articles/im-on-a-boat: onaboat
  A-Tour-Through-the-Windows-8-Documentation: win8docstour
  Ban-the-Region: banregion
  big-windows-developer-event-in-la: laevent2012
  codechat: http://channel9.msdn.com/shows/codechat
  win8camp: windows-8-2-day-camp-content
  Welcome-to-BlogEngineNET-27/: /blogengine/
  Random-Tile-Colors/: /randomtilecolors
  Styling-the-ListView/: /listviewstyle/
  The-Ocho: ocho
  The-Counter-Principles-of-Metro-Style-Design/: /counterprinciples/
  I-give-you-my-word/: /myword/
  Update-on-ReSharper-7-EAP/: /rs7eap/
  Good-Design-for-App-Bar-Button-Placement/: /appbarbuttons/
  Get-An-App-Into-the-Windows-8-Store/: /appinstore/
  Ban-the-Region/: /banregion/
  big-windows-developer-event-in-la/: /laevent2012/
  A-Tour-Through-the-Windows-8-Documentation/: /win8docstour/
  Design-Before-You-Develop/: /designdev/
  Save-New-Projects-When-Created/: /vsnewproj/
  creating-a-timer-in-windows-8-c/: /win8timer/
  So-Many-Ways-to-Search-in-Visual-Studio-11/: /vssearch/
  you-cant-beat-free-html5css3-training/: /cantbeatfree/
  All-About-Scope: scope
  Dynamic-Link-to-Internet-Calendars/: /callink/
  Print-the-Screen-in-Windows-8/: /win8printscreen/
  completed-the-move-wordpress-to-blogengine-net/: /blogengine/
  query-selector-helper-for-metro-apps/: /q/
  deviceinfo/netflixstage1/: /netflixstage1/
  Adding-a-New-Page-in-Windows-8: newpageinwin8
  using-promises/: /usingpromises/
  page/resources.aspx/: /resources/
  page/resources/: /resources/
  Visual-Studio-11-Ninja-Skills/: /vsninja/
  Which-Windows-8-Language-Stack-Should-I-Choose/: /whichstack/
  Creating-an-Observable-Object-in-Windows-8-JavaScript/: /observables/
  A-Primer-on-LINQ-and-Lambda/: /linqlambda/
  Page-Navigation/: /win8pagenav/
  sweetstacksoon/: /sweetstack/
  onesweetstack/: /sweetstack/
  articles/im-on-a-boat/: /onaboat/
  oscon2014rearview/: /codechat/oscon/
  get-that-winrt-documentation-local: docslocal
  avatar/: http://codefoster.blob.core.windows.net/site/image/abcf6a96083749889590d13c8cbbe054/atlanta_1.png
  deck/scc15/: http://1drv.ms/1WKzRCO
  deck/svcc15/: http://1drv.ms/1PM1tCl
  vectortof360/: http://codefoster.blob.core.windows.net/site/file/9684f45088c94e539e2346bf6802cc8b/VectorToF360.mp4?sv=2012-02-12&st=2015-12-23T14%3A36%3A04Z&se=2015-12-23T14%3A47%3A04Z&sr=b&sp=r&sig=8Yl%2FrkkeOsXxtG5VUdTIzliw2z%2FcfpqlqooEbbAYV8o%3D
  goprodrop/: https://onedrive.live.com/redir?resid=C396A8DE1E2DADF4!892089&authkey=!ABBouAkZbLtpedo&ithint=video%2cmp4
  deck/sjs-observables/: https://onedrive.live.com/redir?resid=C396A8DE1E2DADF4!891980&authkey=!AH-BvdKl_YRAEGs&ithint=file%2cpptx
  vorlonjs/: https://channel9.msdn.com/shows/codechat/046
  thatdeck/: https://1drv.ms/p/s!AvStLR7eqJbDvZpYugyJScQ6WQto1g
  scc16/: https://1drv.ms/f/s!AvStLR7eqJbDvbMhBbXwquwnEgds9g
  githubmva/: https://mva.microsoft.com/en-US/training-courses/github-for-windows-users-16749?l=KTNeW39wC_6006218965
  sea-node-deck/: https://1drv.ms/p/s!AvStLR7eqJbDvuhlY39bpgMRq7pZgg
  shs/: https://1drv.ms/p/s!AvStLR7eqJbDvux28J4d7whKeKH_ug
  svccslides/: https://1drv.ms/f/s!AvStLR7eqJbDvuI_lNt9Aw-17w4YZg
  valdez-balance/: https://codefoster-functions.azurewebsites.net/api/valdez-balance
  darnmouse/: https://1drv.ms/p/s!AvStLR7eqJbDv4o_FqCRIck2h3xmkg
  tsconfig/: https://gist.github.com/codefoster/ed5f795ff72e6aba78c81a9fc3792613
  ngmeetup/: https://1drv.ms/p/s!AvStLR7eqJbDvt4DkuTbBC8J_ZBpZA
  pdxjs/: https://1drv.ms/p/s!AvStLR7eqJbDw-c0oG3hLiE2iSSMqw
  pdxnode/: https://1drv.ms/p/s!AvStLR7eqJbDw-16gS30qVUPCawV1A
  cdsummit/: https://1drv.ms/p/s!AvStLR7eqJbDxKwsRp-VWzCDDeVnmA
  codechat/: http://channel9.msdn.com/shows/codechat
  codechat/feed/: http://s.ch9.ms/Shows/codechat/RSS
  codechat/feed/audio/: http://s.ch9.ms/Shows/codechat/feed/mp3
  stories: codechat
  codechat/000/: http://channel9.msdn.com/Shows/codechat/000
  codechat/001/: http://channel9.msdn.com/Shows/codechat/001
  codechat/002/: http://channel9.msdn.com/Shows/codechat/Episode-002-Jason-Short-The-Cloud-
  codechat/003/: http://channel9.msdn.com/shows/codechat/003
  codechat/004/: http://channel9.msdn.com/shows/codechat/004
  codechat/005/: http://channel9.msdn.com/shows/codechat/005
  codechat/006/: http://channel9.msdn.com/shows/codechat/006
  codechat/007/: http://channel9.msdn.com/shows/codechat/007
  codechat/008/: http://channel9.msdn.com/Shows/codechat/008
  codechat/009/: http://channel9.msdn.com/shows/codechat/009
  codechat/010/: http://channel9.msdn.com/shows/codechat/010
  codechat/011/: http://channel9.msdn.com/shows/codechat/011
  codechat/012/: http://channel9.msdn.com/shows/codechat/012
  codechat/013/: http://channel9.msdn.com/shows/codechat/013
  codechat/014/: http://channel9.msdn.com/shows/codechat/014
  codechat/015/: http://channel9.msdn.com/shows/codechat/015
  codechat/016/: http://channel9.msdn.com/shows/codechat/016
  codechat/017/: http://channel9.msdn.com/shows/codechat/017
  codechat/018/: http://channel9.msdn.com/shows/codechat/018
  codechat/019/: http://channel9.msdn.com/shows/codechat/019
  codechat/020/: http://channel9.msdn.com/shows/codechat/020
  codechat/021/: http://channel9.msdn.com/shows/codechat/021
  codechat/022/: http://channel9.msdn.com/shows/codechat/022
  codechat/023/: http://channel9.msdn.com/shows/codechat/023
  codechat/024/: http://channel9.msdn.com/Shows/codechat/024
  codechat/025/: http://channel9.msdn.com/Shows/codechat/CodeChat-025-Andy-Wilson-Rexter
  codechat/026/: http://channel9.msdn.com/Shows/codechat/026
  codechat/027/: https://channel9.msdn.com/Shows/codechat/027
  codechat/028/: http://channel9.msdn.com/shows/codechat/028
  codechat/029/: http://channel9.msdn.com/shows/codechat/029
  codechat/030/: http://channel9.msdn.com/shows/codechat/030
  codechat/031/: http://channel9.msdn.com/shows/codechat/031
  codechat/032/: http://channel9.msdn.com/shows/codechat/032
  codechat/033/: http://channel9.msdn.com/shows/codechat/033
  codechat/034/: http://channel9.msdn.com/shows/codechat/034
  codechat/035/: http://channel9.msdn.com/shows/codechat/035
  codechat/036/: http://s.ch9.ms/shows/codechat/036
  codechat/037/: http://s.ch9.ms/shows/codechat/037
  codechat/038/: http://channel9.msdn.com/shows/codechat/038
  codechat/039/: http://channel9.msdn.com/shows/codechat/039
  codechat/codegalaxies/: https://channel9.msdn.com/shows/codechat/039
  codechat/040/: http://channel9.msdn.com/shows/codechat/040
  codechat/041/: http://channel9.msdn.com/shows/codechat/041
  codechat/042/: http://channel9.msdn.com/shows/codechat/042
  codechat/043/: http://channel9.msdn.com/shows/codechat/043
  codechat/044/: http://channel9.msdn.com/shows/codechat/044
  codechat/045/: http://channel9.msdn.com/shows/codechat/045
  codechat/046/: http://channel9.msdn.com/shows/codechat/046
  codechat/047/: http://channel9.msdn.com/shows/codechat/047
  codechat/048/: http://channel9.msdn.com/shows/codechat/048
  codechat/049/: http://channel9.msdn.com/shows/codechat/049
  codechat/050/: http://channel9.msdn.com/shows/codechat/050
  codechat/rx/: https://channel9.msdn.com/shows/codechat/050
  codechat/051/: http://channel9.msdn.com/shows/codechat/051
  codechat/thali/: https://channel9.msdn.com/shows/codechat/051
  codechat/052/: http://channel9.msdn.com/shows/codechat/052
  codechat/053/: http://channel9.msdn.com/shows/codechat/053
  codechat/054/: http://channel9.msdn.com/shows/codechat/054
  codechat/055/: http://channel9.msdn.com/shows/codechat/055
  codechat/056/: http://channel9.msdn.com/shows/codechat/056
  codechat/057/: http://channel9.msdn.com/shows/codechat/057
  codechat/058/: http://channel9.msdn.com/shows/codechat/058
  codechat/atlmic/: http://channel9.msdn.com/shows/codechat/058
  codechat/059/: http://channel9.msdn.com/shows/codechat/059
  codechat/060/: http://channel9.msdn.com/Shows/codechat/060
  codechat/061/: http://channel9.msdn.com/Shows/codechat/061
  codechat/062/: http://channel9.msdn.com/Shows/codechat/062
  codechat/063/: http://channel9.msdn.com/Shows/codechat/063
  codechat/064/: http://channel9.msdn.com/Shows/codechat/064
  codechat/065/: http://channel9.msdn.com/Shows/codechat/065
  codechat/066/: http://channel9.msdn.com/Shows/codechat/066
  codechat/067/: http://channel9.msdn.com/Shows/codechat/067
  codechat/068/: http://channel9.msdn.com/Shows/codechat/068
  codechat/069/: http://channel9.msdn.com/Shows/codechat/069
  codechat/070/: http://channel9.msdn.com/Shows/codechat/070
  codechat/071/: http://channel9.msdn.com/Shows/codechat/071
  codechat/072/: http://channel9.msdn.com/Shows/codechat/072
  codechat/073/: http://channel9.msdn.com/Shows/codechat/073
  codechat/074/: http://channel9.msdn.com/Shows/codechat/074
  codechat/075/: http://channel9.msdn.com/Shows/codechat/075
  codechat/076/: http://channel9.msdn.com/Shows/codechat/076
  codechat/077/: http://channel9.msdn.com/Shows/codechat/077
  codechat/078/: http://channel9.msdn.com/Shows/codechat/078
  codechat/079/: http://channel9.msdn.com/Shows/codechat/079
  post/2012/05/23/Windows-8-Top-10-Reasons-why-I-choose-HTML5-over-XAML.aspx/: /htmloverxaml/
  post/2013/01/08/loadingstates.aspx/: /loadingstates/
  post/2012/08/31/givecamp/: /givecamp/
  post/2012/07/12/Random-Tile-Colors.aspx/: /random-tile-colors/
  post/2012/11/20/media/: /media/
  post/2012/06/05/win8keys.aspx/: /win8keys/
  post/2012/06/29/How-the-WinJSUIViewBox-Actually-Works.aspx/: /viewboxhow/
  post/2012/08/18/win8icons.aspx/: /win8icons/
  post/2013/03/18/pushusers/: /pushusers/
  post/2013/04/15/appart/: /appart/
  post/2012/03/29/So-Many-Ways-to-Search-in-Visual-Studio-11.aspx/: /vssearch/
  post/2012/08/23/nth-child/: /nthchild/
  post/2013/02/11/ready/: /ready/
  post/2012/05/22/Windows-8-Building-Up-to-Blank.aspx/: /blank/
  post/2012/03/16/All-About-Scope.aspx/: /scope/
  post/2012/05/29/I-give-you-my-word.aspx/: /myword/
  post/2012/09/20/dyyno.aspx/: /dyyno/
  post/2012/08/22/panning/: /panning/
  post/2012/11/09/exams/: /exams/
  post/2012/06/13/semanticzoom.aspx/: /semanticzoom/
  post/2012/06/22/Using-Promises.aspx/: /usingpromises/
  post/2012/09/14/datapresentation.aspx/: /datapresentation/
  post/2012/11/12/flexboxstandard.aspx/: /flexboxstandard/
  post/2012/09/06/packagefiles/: /packagefiles/
  post/2012/03/30/Insert-Formatted-Code-into-OneNote.aspx/: /codeinonenote/
  post/2012/04/11/Simple-Netflix-Browser-in-Windows-8-JavaScript-Part-1.aspx/: /netflixstage1/
  post.aspx/: /blog/
  post/2012/03/27/ReSharper-7-EAP-in-Visual-Studio-11/: /resharper-7-eap-in-visual-studio-11/
  post/2012/03/30/Yay-Syntax-Highlighting/: /Yay-Syntax-Highlighting/
  post/2012/04/04/Snippets-Overview-in-VS11-and-ReSharper.aspx/: /snippets/
  post/2012/06/12/boxes/: /boxes/
  post/2012/06/13/Styling-the-ListView/: /listviewstyle/
  post/2012/06/13/netflixstage1/: /netflixstage1/
  post/2012/10/01/community.aspx/: /community/
  post/feed/2012/06/18/fastrefresh/: /fastrefresh/
  post/feed/2012/09/20/jumpstart/: /jumpstart/
  post/feed/2012/09/24/query/: /query/
  post/feed/2012/09/26/xhr/: /xhr/
  post/feed/2012/11/12/genappdesign/: /genappdesign/
  post/feed/2013/01/10/cssbookcode/: /cssbookcode/
  post/2012/06/12/boxes.aspx/: /boxes/
  post/2012/11/19/familyapp.aspx/: /familyapp/
  post/2012/03/30/Insert-Formatted-Code-into-OneNote/: /codeinonenote/
  post/feed/2012/11/12/flexboxstandard/: /flexboxstandard/
  post/feed/2012/11/09/exams/: /exams/
  post/feed/2012/09/20/dyyno/: /dyyno/
  post/feed/2012/09/14/datapresentation/: /datapresentation/
  post/2012/11/19/familyapp/: /familyapp/
  post/2012/05/29/I-give-you-my-word/: /myword/
  post/feed/2012/06/22/Using-Promises/: /usingpromises/
  post/2012/06/21/Page-Navigation-in-Windows-8-JavaScript-Apps/: /win8pagenav/
  post/2012/06/21/Page-Navigation-in-Windows-8-JavaScript-Apps.aspx/: /win8pagenav/
  post/2012/04/09/Design-Before-You-Develop.aspx/: /designdev/
  post/2012/04/09/Design-Before-You-Develop/: /designdev/
  post/2012/09/20/jumpstart/: /jumpstart/
  post/2012/12/11/dontpanic/: /dontpanic/
  post/2012/12/11/dontpanic.aspx/: /dontpanic/
  post/2012/10/01/eventHandlers.aspx/: /eventhandlers/
  post/2012/10/01/eventHandlers/: /eventhandlers/
  post/2012/04/05/Save-New-Projects-When-Created.aspx/: /vsnewproj/
  post/2012/04/05/Save-New-Projects-When-Created/: /vsnewproj/
  post/2013/02/11/ready.aspx/: /ready/
  post/2012/03/15/Dynamic-Link-to-Internet-Calendars.aspx/: /callink/
  post/2012/03/15/Dynamic-Link-to-Internet-Calendars/: /callink/
  post/2012/10/02/swipe/: /swipe/
  post/2012/10/02/swipe.aspx/: /swipe/
  post/2012/06/28/designsheet.aspx/: /designsheet/
  post/2012/03/27/SecondScreenMetro.aspx/: /secondscreenmetro/
  post/2012/08/29/snappoints.aspx/: /snappoints/
  post/2012/06/21/sweetstack.aspx/: /sweetstack/
  post/2013/07/08/noise/: /noise/
  post/2012/11/15/anatomyofpush.aspx/: /anatomyofpush/
  post/2012/09/26/storage.aspx/: /storage/
  post/2012/11/20/escalator.aspx/: /escalator/
  post/2012/12/19/cssbook/: /cssbook/
  post/2012/05/30/the-counter-principles-of-metro-style-design.aspx/: /counterprinciples/
  post/2012/12/06/camview/: /camview/
  post/2012/06/13/netflixstage1.aspx/: /netflixstage1/
  post/2012/09/14/datapresentation/: /datapresentation/
  post/2012/03/09/Adding-a-New-Page-in-Windows-8.aspx/: newpageinwin8
  post/2012/05/23/Windows-8-Top-10-Reasons-why-I-choose-HTML5-over-XAML/: /htmloverxaml/
  post/feed/2012/06/05/tabletphilosophy.aspx/: /tabletphilosophy/
  post/2012/08/22/panning.aspx/: /panning/
  post/2012/06/22/Using-Promises/: /usingpromises/
  post/2012/03/15/Selecting-Elements-in-a-Windows-8-HTML-App/: /selectingelements/
  post/feed/2012/06/22/Using-Promises.aspx/: /usingpromises/
  post/2012/12/27/stilljs.aspx/: /stilljs/
  post/2013/01/08/loadingstates/: /loadingstates/
  post/2012/05/21/Good-Design-for-App-Bar-Button-Placement.aspx/: /appbarbuttons/
  post/2012/10/26/tryunsnap.aspx/: /tryunsnap/
  post/2012/04/25/Which-Windows-8-Language-Stack-Should-I-Choose/: /whichstack/
  post/2012/03/15/Selecting-Elements-in-a-Windows-8-HTML-App.aspx/: /selectingelements/
  post/2012/11/15/anatomyofpush/: /anatomyofpush/
  post/2012/05/17/App-Accelerator-Resources/: /App-Accelerator-Resources/
  post/2012/11/20/discover.aspx/: /discover/
  post/2012/06/29/How-the-WinJSUIViewBox-Actually-Works/: /viewboxhow/
  post/2012/08/18/win8icons/: /win8icons/
  post/2012/09/06/packagefiles.aspx/: /packagefiles/
  post/2012/11/20/escalator/: /escalator/
  post/2012/11/06/Box-Sizing.aspx/: /boxsizing/
  post/2012/11/20/media.aspx/: /media/
  post/2012/09/26/storage/: /storage/
  post/2012/04/10/Creating-an-Observable-Object-in-Windows-8-JavaScript.aspx/: /observables/
  post/2012/06/13/semanticzoom/: /semanticzoom/
  post/2012/08/06/Windows-8-2-day-Camp-Content.aspx/: /windows-8-2-day-camp-content/
  post/2012/10/04/telerik.aspx/: /telerik/
  post/2012/06/28/metrosheet.aspx/: /designsheet/
  post/feed/2012/04/26/Get-That-WinRT-Documentation-Local: docslocal
  post/2012/05/30/The-Counter-Principles-of-Metro-Style-Design/: /The-Counter-Principles-of-Metro-Style-Design/
  post/2012/05/02/Query-Selector-Helper-for-Metro-Apps.aspx/: /Query-Selector-Helper-for-Metro-Apps.aspx/
  post/2012/09/26/xhr.aspx/: /xhr/
  post/2012/08/13/holo.aspx/: /holo/
  post/feed/2012/12/19/cssbook/: /cssbook/
  post/2012/05/13/Windows-8-Camp-Content.aspx/: /Windows-8-Camp-Content/